# Generated by Django 3.2 on 2022-05-24 04:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='diary/')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('real_date', models.DateField()),
                ('emoji', models.ImageField(blank=True, null=True, upload_to='')),
                ('positive', models.FloatField(blank=True, null=True)),
                ('negative', models.FloatField(blank=True, null=True)),
                ('neutral', models.FloatField(blank=True, null=True)),
                ('advice', models.CharField(max_length=200)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diaries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
