# Generated by Django 3.2 on 2022-05-24 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='advice',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
