# Generated by Django 3.2 on 2022-05-25 13:26

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diaryapp', '0003_alter_diary_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='title',
        ),
        migrations.AddField(
            model_name='diary',
            name='color',
            field=colorfield.fields.ColorField(blank=True, default=None, image_field=None, max_length=18, null=True, samples=None),
        ),
        migrations.AddConstraint(
            model_name='diary',
            constraint=models.UniqueConstraint(fields=('writer', 'real_date'), name='unique_diary'),
        ),
    ]
